//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dropdown2ndpage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class favlist
    {
        public int Id { get; set; }
        public string movietitle { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> movieID { get; set; }
    
        public virtual usertable usertable { get; set; }
    }
}
