//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dropdown2ndpage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class moviename
    {
        public int Id { get; set; }
        public string Language { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<double> Ratings { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Likes { get; set; }
    }
}
