//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDdemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using common;
    public class EmployeeMetaData
    {
        [StringLength(15, MinimumLength = 3)]
        [Required]
        [RegularExpression(@"^(([A-Za-z]+[\s]{1}[A-Za-z]+)|([A-Za-z]+))$", ErrorMessage = "name should contain only characters and space")]
        public string FullName { get; set; }

        [DisplayFormat(NullDisplayText = "Gender not specified")]
        public string Gender { get; set; }

        [Range(12000, 100000)]
        public int Salary;

        [Range(20, 60)]
        public int? Age { get; set; }

        //[CurrentDate(ErrorMessage = "wrong date")]
        [Range(typeof(DateTime), "01/01/2015", "02/10/2019")]
        public Nullable<System.DateTime> HireDate { get; set; }

        [RegularExpression(@"^[\w-\._\+%]+@(?:[\w-]+\.)+[\w]{2,6}$", ErrorMessage = "Enter valid email id")]
        public string EmailAddress { get; set; }
     
    }
    [MetadataType(typeof(EmployeeMetaData))]
    public partial class DemotblEmployee
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> Salary { get; set; }
        public string PersonalWebSite { get; set; }
        public string Photo { get; set; }
        public string AlternateText { get; set; }
    }
}
