//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Number_products { get; set; }
        public int SupplierId { get; set; }
        public int ProductId { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual Product Product { get; set; }
    }
}
