//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginFrontPage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public class CorporateMetaData
    {
        [StringLength(15, MinimumLength = 4)]
        [Required]
        [RegularExpression(@"^(([A-Za-z]+[\s]{1}[A-Za-z]+)|([A-Za-z]+))$", ErrorMessage = "Enter valid Full Name")]
        public string FullName { get; set; }

        [Required]
        public string Gender { get; set; }


        [Required]
        [DataType(DataType.Date)]
        public DateTime? DOB { get; set; }

        [Required]
        [RegularExpression(@"^[\w.+\-]+@gmail\.com$", ErrorMessage = "Enter valid Gmail Id")]
        public string Email { get; set; }

        [Required]
        [RegularExpression(@"^[0-9]{10}$", ErrorMessage = "Enter valid Mobile Number")]
        public Nullable<long> Mobile { get; set; }

        //[Required]
        //[RegularExpression(@"^\\d+(\\.\\d+)?", ErrorMessage = "Enter valid Percentage")]
        //public Nullable<double> GradPerc { get; set; }

        [Range(2000, 2019)]
        public Nullable<int> GradPassesYear { get; set; }


        [Range(0, 20)]
        public Nullable<int> ExpYears { get; set; }



        [Required]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[#$^+=!*()@%&]).{8,14}$", ErrorMessage = "Enter valid Password")]
        public string Password { get; set; }

        public HttpPostedFileBase file { get; set; }
        //[NotMapped]
        //[Required]
        //[Compare("Password")]
        //public string ConfirmPassword { get; set; }

    }
    [MetadataType(typeof(CorporateMetaData))]
    public partial class Corporate
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Email { get; set; }
        public Nullable<long> Mobile { get; set; }
        public Nullable<double> GradPerc { get; set; }
        public string GradDegree { get; set; }
        public string GradBranch { get; set; }
        public Nullable<int> GradPassesYear { get; set; }
        public string TechStack1 { get; set; }
        public string TechStack2 { get; set; }
        public string TechStack3 { get; set; }
        public string PrevCompany { get; set; }
        public Nullable<int> ExpYears { get; set; }
        public string Password { get; set; }
        public string otp { get; set; }
        public string ConfirmPassword { get; set; }
        public HttpPostedFileBase file { get; set; }
        public string Resume { get; set; }
        
    }
}
